### ISSUE TITLE
Замечания по второму заданию

### ISSUE THREAD

**Issue by maximpetrov** [AlexPentagon/MyStudyJavaProject#2]
1. Лучше прямо в `main` создать `BufferedReader` и `BufferedWriter` в зависимости от аргументов из файла или из консоли и передавать в методы `Uniq` уже их независимо от опций. Кстати, передаваемый параметр `output` даже сейчас не используется.
1. Не вижу смысла делать `searchWithout` отдельным полем, если можно просто проверить `searchNum` на больше 0.
1. Зачем здесь `forEachOrdered` вместо `forEach`?
https://github.com/AlexPentagon/MyStudyJavaProject/blob/e9582ea962db190b68b8888a3db1554058b23d74/src/Task2/Uniq.java#L38
1. Вместо `"\r\n"` лучше использовать метод `newLine`.
1. Было бы красивее, если бы метод `uniq` только считал строки и возвращал список пар <строка, число повторений>. А уже метод `writeFile` выводил бы нужные строки (все или уникальные) в нужном формате (в числом или без). В этом случае и параметры `uniqLines` и `countLines` логичнее передавать в метод `writeFile`, а не в конструктор.
1. Вы что-то перемудрили в `uniq` со стеками. Во-первых, класс `Stack` устаревший и вместо него стоит использовать, например, `ArrayDeque`. Во-вторых, зачем Вам здесь вообще стек, Вам и `ArrayList` подойдёт. Даже в том варианте, который у Вас сейчас есть, `ArrayList` позволяет смотреть последний элемент и удалять его. Но лучше просто сохранить в переменной последнюю добавленную пару и увеличивать в ней счётчик (Вы ведь создаёте изменяемую `MutablePair`). Или можно просто хранить последнюю обрабатываемую строку и счётчик в переменных, а при нахождении отличающейся строки добавлять в `ArrayList`. А ещё, зачем Вы вставляете для строки пару со значением 0, чтобы потом сразу её переписать, увеличив до 1? И зачем Вам переменная `counter`, которая всегда равна 1?
1. Зачем так сложно получать подстроку, если есть `substring`?
https://github.com/AlexPentagon/MyStudyJavaProject/blob/e9582ea962db190b68b8888a3db1554058b23d74/src/Task2/Uniq.java#L74-L79
1. Переводом в нижний регистр и вырезанием подстроки Вы портите строку, которую нужно вывести в исходном виде.
1. При переводе из списка пар в список строк Вы обрабатываете `uniqLines` и `countLines` как связанные параметры, перебирая все их сочетания и дублируя код. На самом деле они независимы и можно сначала проверить, что строку нужно выводить, а потом уже, если нужно, вывести с префиксом или без.
1. В задании этого явно не сказано, но лучше отделить префикс пробелом или табуляцией, чтобы он не смешивался с возможными "значащими" цифрами в начале строки.
1. Ошибки нужно выводить пользователю в виде понятных сообщений, а не в виде стек-трейса с выпавшим исключением.

**Comment by AlexPentagon** [comment]
Сначала хотел спорить по большинству пунктов (так как они не получались))) но теперь все выглядит и правда лучше. Спасибо :)
1  `output` исправил.
2 исправлено.
3 исправлено.
4 исправлено.
5 исправлено. 
6 исправлено

>  А ещё, зачем Вы вставляете для строки пару со значением 0, чтобы потом сразу её переписать, увеличив до 1?

чтобы уменьшить цифру первой строки в результате (не знаю как по-другому)


7 иначе  лишние сложности с обработкой исключений,возникающих при `searchNum > line`
8 с флагом "-s" согласен,и прочитав задание убедился , что нужно выводить первую строку(но я не знаю как это сделать не продублировав код) , но все равно это выглядит не так уж плохо
9. исправлено
10 исправлено.
11 исправлено.

после всех изменений еще больше не понимаю как написать тесты

**Comment by maximpetrov** [comment]
1. Я забыл в прошлый раз написать, что Вы всегда считаете, что последний аргумент командной строки - это входной файл, хотя это не так, а из консоли читаете при любой ошибке при чтении этого файла. Читать из консоли нужно тогда и только тогда, когда имя входного файла не задано в аргументах. При ошибке чтения файла нужно выдавать ошибку чтения.
1. Я не настаиваю, чтобы Вы переносили создание `BufferedReader` и `BufferedWriter` (пункт 1) в `main`, но избавиться от дублирования кода в `read`/`readComLine` и особенно в `writeFile`/`writeCons` всё равно нужно.
1. Ещё раз по поводу подсчёта повторений (6 пункт). Во-первых, что мешает Вам поместить сравнение текущей строки с предыдущей в `else` того `if`, который проверяет `result` на пустоту? Тогда можно будет в нём просто положить в `result` строку с количеством 1 и больше ничего не делать. Во-вторых, сохраните в переменную результат `result.get(counter)`, вместо того, чтобы 3 раза его переполучать. В-третьих, все объекты в `Java` передаются по ссылкам, а в списке у Вас лежат `MutablePair`, которые можно не только создавать, но и менять. Таким образом, вместо того, чтобы создавать новую пару, удалять старую и класть новую на её место, можно просто вызвать на паре метод `setRight` и больше ничего делать не нужно.
1. В чём сложность с обработкой исключений? Написать `try/catch`? Тем более, что лучше вообще просто проверить это самое условие (`searchNum > line`), чем выбрасывать и ловить тяжеловесное исключение. Это уж точно проще, чем создавать несколько временных объектов.
1. Пункт 8 исправить всё равно нужно, самый простой способ - хранить строки в исходном виде, а перед сравнением переводить в нижний регистр и обрезать.
1. Проверку флага `-u` и проверку количества строк на 1 можно объединить так, чтобы не пришлось дублировать код.
1. Обработку исключений Вы сделали неправильно, стало даже хуже, чем было. Большинство методов большинства классов не должны выводить ничего на консоль, разве что отладочную информацию и то только в отладочном режиме. Во-первых, если кто-то будет использовать Ваш класс он скорее всего будет сам выводить что-нибудь на консоль и, особенно если его консольный вывод будет важен для пользователя, он вряд ли захочет увидеть посреди своего красивого форматированного вывода Ваш, которым управлять он никак не может. Во-вторых, ещё хуже делать так, как делаете сейчас Вы - сообщать в консоль об ошибках и больше ничего не делать. Код, который вызывает Ваши методы, никак не сможет узнать, что что-то пошло не так, потому что консоль увидит только пользователь. А ему это знать нужно, потому что дальнейшая обработка результата метода обычно бессмысленна, а может и привести к ошибкам. Итого: исключения должны перехватываться там, где с этой ошибкой можно что-то сделать. Если Вы хотите перехватить исключение, чтобы вывести ошибку пользователю, то делать это нужно в `main`, который у Вас отвечает за пользовательский интерфейс.

**Comment by maximpetrov** [comment]
По поводу тестов: если отбросить случаи с работой с консолью, то всё достаточно просто: создаёте набор тестовых входных файлов, набор файлов с ожидаемыми результатами и вызываете `main`, а потом сравниваете ожидаемый файл с получившимся. С консолью чуть сложнее: нужно подменить в тесте `System.in` и `System.out` на строковые или файловые потоки.

**Comment by AlexPentagon** [comment]
вроде все исправлено,запуская методы `read()/write()` из тестов получаю вечный цикл

**Comment by maximpetrov** [comment]
На самом деле, Вы исправили только половину замечаний. По поводу бесконечного цикла в тестах ничего сказать не могу, Вы их в таком виде не закоммитили.

1. Пункт 2 исправлен наполовину: `read` Вы переделали, а во `write` почему-то всё ещё в каждом месте использования выясняете куда писать.
1. Пункты 3, 6 и 7 Вы проигнорировали целиком.
1. Посмотрите внимательно на использование переменной `comparList`. Вы либо добавляете элемент в конец, либо смотрите на последний элемент. Раз Вы работаете только с последним элементом, можно вместо списка просто хранить последнюю строку.
1. Вместо того, чтобы передавать два аргумента (консоль/не консоль и имя файла), лучше обойтись одним аргументом (имя файла), передавая в него `null` для задания консольного ввода или вывода. Кроме того, не понятно, почему вдруг флаг консоль/не консоль передаётся в конструктор, а имя файла во `write`.
